# Generated by Django 4.0.1 on 2022-01-26 03:30

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default_user.jpg', upload_to=core.models.user_directory_path)),
                ('roll_number', models.CharField(max_length=50, null=True, unique=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('bus_number', models.IntegerField(null=True)),
                ('rfid', models.CharField(max_length=50, null=True, unique=True)),
                ('is_fees_paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], default='present', max_length=8)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
    ]
