# Generated by Django 4.0.1 on 2022-01-05 11:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default_user.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
